### PR TITLE
Css Lessons

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**
Screenshot_20220129-001018_Chrome

### CODE REVIEW

**Comment by AbdullahM0hamed** [comment]
Lmao, forgot to commit the meat of this PR

**Comment by nate-moo** [comment]
~~this is being weird, 2 of those commits are merged already, should it matter or will it know and not care~~

fixed with merge from upstream

**Comment by justfoolingaround** [comment]
`a[id="id"], a[href^="li"], a[href$="nk"]` 💂🏿‍♂️

**Pull request merged**
